// internal/apply/apply.go

// Package apply assembles everything needed to complete one job
// application by hand (generated documents + the posting open in a
// browser) — see docs/mastermind/specs/2026-09-05-apply-automation-design.md
// for why this phase deliberately does not auto-fill or auto-submit
// anything.
package apply

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/monoes/mono-agent/internal/documents"
	"github.com/monoes/mono-agent/internal/vault"
)

// Prepare ensures applicationID has a generated CV and cover letter in
// the vault, generating them now if none exist yet for this application
// (checked via vault.ListDocuments filtered by ApplicationID) — calling
// Prepare twice on the same application reuses the existing documents
// rather than creating duplicates.
func Prepare(ctx context.Context, db *sql.DB, profileID, applicationID string, cvData documents.CVData, coverLetterData documents.CoverLetterData) (cvHTMLID, cvPDFID, letterHTMLID, letterPDFID string, err error) {
	existing, err := vault.ListDocuments(ctx, db, profileID)
	if err != nil {
		return "", "", "", "", fmt.Errorf("apply.Prepare: listing existing documents: %w", err)
	}

	// A generated document's Source is always "generated" (set by
	// documents.GenerateDocument via vault.RegisterDocument) — Phase 3's
	// manually-uploaded profile documents use Source "upload" and are
	// never mistaken for a prior CV/cover-letter generation here.
	var forApp []vault.DocumentEntry
	for _, d := range existing {
		if d.ApplicationID == applicationID && d.Source == "generated" {
			forApp = append(forApp, d)
		}
	}

	// Two documents (CV, cover letter) each produce two vault entries
	// (HTML, PDF) in creation order: cv-html, cv-pdf, letter-html,
	// letter-pdf (documents.GenerateDocument always registers HTML then
	// PDF; Prepare always generates CV then cover letter below) — so 4
	// existing entries for this application means both were already
	// generated by a prior Prepare call.
	if len(forApp) >= 4 {
		// ListDocuments orders newest-first; the most recent 4 are this
		// application's most recent CV+letter pair in reverse creation
		// order (letter-pdf, letter-html, cv-pdf, cv-html).
		return forApp[3].ID, forApp[2].ID, forApp[1].ID, forApp[0].ID, nil
	}

	cvHTMLID, cvPDFID, err = documents.GenerateDocument(ctx, db, profileID, applicationID, documents.DocTypeCV, cvData)
	if err != nil {
		return "", "", "", "", fmt.Errorf("apply.Prepare: generating cv: %w", err)
	}
	letterHTMLID, letterPDFID, err = documents.GenerateDocument(ctx, db, profileID, applicationID, documents.DocTypeCoverLetter, coverLetterData)
	if err != nil {
		return cvHTMLID, cvPDFID, "", "", fmt.Errorf("apply.Prepare: generating cover letter: %w", err)
	}
	return cvHTMLID, cvPDFID, letterHTMLID, letterPDFID, nil
}
