#!/usr/bin/env bash
# install.sh — install the mono-agent CLI (monoagentcli) from the latest
# GitHub release of monoes/mono-agent.
#
# Supported platforms (must match the asset names built by
# .github/workflows/release.yml):
#   darwin/arm64  → monoagentcli-darwin-arm64
#   darwin/amd64  → monoagentcli-darwin-amd64
#   linux/amd64   → monoagentcli-linux-amd64
#   linux/arm64   → monoagentcli-linux-arm64
# Anything else fails loudly (Windows: download the .exe from the releases page).
#
# Every release ships a SHA256SUMS.txt (generated by release.yml); the
# downloaded binary is verified against it before install. If that file is
# missing (release predates checksum publication) the install hard-fails
# unless --no-verify is given.
#
# Flags:
#   --no-verify   skip SHA256SUMS.txt verification (not recommended)
#
# Override the install location:  INSTALL_DIR="$HOME/bin" ./install.sh
set -euo pipefail

REPO="monoes/mono-agent"
BIN="monoagentcli"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"

err() { printf 'install.sh: error: %s\n' "$*" >&2; exit 1; }

NO_VERIFY=0
for arg in "$@"; do
  case "$arg" in
    --no-verify) NO_VERIFY=1 ;;
    *)            err "unknown option '$arg' (supported: --no-verify)" ;;
  esac
done

command -v curl >/dev/null 2>&1 || err "curl is required but not installed"

# verify_checksum <dir> <asset> — check <dir>/<asset> against the <asset>
# line in <dir>/SHA256SUMS.txt (format: "<sha256>  <filename>", as written
# by sha256sum / shasum). Prints the verified digest on success; returns
# non-zero (with a message on stderr) on mismatch, missing entry, or
# missing checksum tool.
verify_checksum() {
  v_dir="$1"
  v_asset="$2"
  v_line="$(grep "[[:space:]]${v_asset}\$" "${v_dir}/SHA256SUMS.txt" | head -n 1 || true)"
  if [ -z "$v_line" ]; then
    printf 'install.sh: error: no checksum entry for %s in SHA256SUMS.txt\n' "$v_asset" >&2
    return 1
  fi
  printf '%s\n' "$v_line" > "${v_dir}/SHA256SUMS.check"

  if command -v sha256sum >/dev/null 2>&1; then
    (cd "$v_dir" && sha256sum -c SHA256SUMS.check) >/dev/null 2>&1
  elif command -v shasum >/dev/null 2>&1; then
    (cd "$v_dir" && shasum -a 256 -c SHA256SUMS.check) >/dev/null 2>&1
  else
    printf 'install.sh: error: neither sha256sum nor shasum is available to verify the download\n' >&2
    return 1
  fi
  v_status=$?

  if [ "$v_status" -ne 0 ]; then
    printf 'install.sh: error: checksum mismatch for %s (expected %s)\n' \
      "$v_asset" "$(printf '%s' "$v_line" | awk '{print $1}')" >&2
    return 1
  fi

  printf '%s\n' "$(printf '%s' "$v_line" | awk '{print $1}')"
}

# ── Detect platform ──────────────────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
  Darwin) os="darwin" ;;
  Linux)  os="linux" ;;
  *)      err "unsupported OS '$OS' (supported: darwin, linux). Windows: download monoagentcli-windows-amd64.exe from the releases page." ;;
esac

case "$ARCH" in
  arm64|aarch64) arch="arm64" ;;
  amd64|x86_64)  arch="amd64" ;;
  *)             err "unsupported architecture '$ARCH' on $os" ;;
esac

ASSET="monoagentcli-${os}-${arch}"

# ── Resolve the latest release ──────────────────────────────────────────────
echo "Resolving latest release of ${REPO}..."
RELEASE_JSON="$(curl --retry 3 --fail --location -fsSL "https://api.github.com/repos/${REPO}/releases/latest")" \
  || err "could not reach the GitHub API (network down, or rate-limited)"

TAG="$(printf '%s' "$RELEASE_JSON" | grep -o '"tag_name": *"[^"]*"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')"
[ -n "$TAG" ] || err "could not parse the latest tag from the GitHub API response"

URL="https://github.com/${REPO}/releases/download/${TAG}/${ASSET}"

# ── Download and verify ──────────────────────────────────────────────────────
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Downloading ${ASSET} (${TAG})..."
# Downloaded under the release asset name so it matches its SHA256SUMS.txt line.
curl --retry 3 --fail --location --progress-bar -o "${TMP_DIR}/${ASSET}" "$URL" \
  || err "download failed: $URL (does this release include the ${ASSET} asset?)"

if [ "$NO_VERIFY" -eq 1 ]; then
  echo "WARNING: --no-verify given — skipping checksum verification." >&2
else
  SUMS_URL="https://github.com/${REPO}/releases/download/${TAG}/SHA256SUMS.txt"
  if ! curl --retry 3 --fail --location -fsSL -o "${TMP_DIR}/SHA256SUMS.txt" "$SUMS_URL"; then
    err "SHA256SUMS.txt not found at ${SUMS_URL} — this release probably predates checksum publication. Refusing to install an unverified binary; re-run with --no-verify to override at your own risk."
  fi
  VERIFIED="$(verify_checksum "${TMP_DIR}" "${ASSET}")" \
    || err "checksum verification FAILED for ${ASSET} — the download does not match ${TAG}'s published digest. Nothing was installed."
  echo "Checksum verified: ${ASSET} SHA256 ${VERIFIED}"
fi

chmod +x "${TMP_DIR}/${ASSET}"

# sudo only when the install dir (or, if it does not exist yet, its closest
# existing parent) is not writable by this user — e.g. INSTALL_DIR=~/.local/bin
# never needs it.
writable_target() {
  d="$1"
  while [ ! -d "$d" ]; do
    parent="$(dirname "$d")"
    [ "$parent" = "$d" ] && return 1
    d="$parent"
  done
  [ -w "$d" ]
}
SUDO=""
if [ "$(id -u)" != "0" ] && ! writable_target "$INSTALL_DIR"; then
  command -v sudo >/dev/null 2>&1 \
    || err "${INSTALL_DIR} is not writable by $(id -un) and sudo is not available — re-run as root, or choose a writable directory with INSTALL_DIR=\$HOME/.local/bin"
  SUDO="sudo"
fi

$SUDO mkdir -p "$INSTALL_DIR" || err "cannot create ${INSTALL_DIR}"
$SUDO mv "${TMP_DIR}/${ASSET}" "${INSTALL_DIR}/${BIN}" || err "cannot install into ${INSTALL_DIR}"

echo "Installed: ${INSTALL_DIR}/${BIN} (${TAG}, ${os}/${arch})"
echo "Verify with:  ${INSTALL_DIR}/${BIN} version"
