package crawl

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
	cfgpkg "github.com/nokhodian/mono-agent/internal/config"
	"github.com/nokhodian/mono-agent/internal/workflow"
)

// ExtractPageNode implements the ai.extract_page workflow node.
// It fetches a web page and extracts structured data using CSS selectors
// (provided directly or generated by the config API).
type ExtractPageNode struct {
	CfgClient *cfgpkg.APIClient
}

func (n *ExtractPageNode) Type() string { return "ai.extract_page" }

func (n *ExtractPageNode) Execute(ctx context.Context, input workflow.NodeInput, config map[string]interface{}) ([]workflow.NodeOutput, error) {
	// --- resolve URL ---
	pageURL, _ := config["url"].(string)
	if pageURL == "" && len(input.Items) > 0 {
		pageURL, _ = input.Items[0].JSON["url"].(string)
	}
	if pageURL == "" {
		return nil, fmt.Errorf("ai.extract_page: url is required (set in config or input item)")
	}

	extractMode, _ := config["extract_mode"].(string)
	if extractMode == "" {
		extractMode = "natural"
	}

	renderMode, _ := config["render_mode"].(string)
	waitSelector, _ := config["wait_selector"].(string)

	// --- fetch ---
	start := time.Now()
	fetchResult, err := FetchPage(ctx, pageURL, FetchOptions{
		RenderMode:   renderMode,
		WaitSelector: waitSelector,
	})
	if err != nil {
		return nil, fmt.Errorf("ai.extract_page: fetch: %w", err)
	}
	fetchMs := time.Since(start).Milliseconds()

	// --- determine selectors ---
	var selectors map[string]string
	listSelector, _ := config["list_selector"].(string)

	switch extractMode {
	case "css":
		selectors, err = parseFieldsConfig(config)
		if err != nil {
			return nil, fmt.Errorf("ai.extract_page: %w", err)
		}

	case "natural":
		if n.CfgClient == nil {
			return nil, fmt.Errorf("ai.extract_page: AI extraction requires the config API client")
		}

		prompt, _ := config["prompt"].(string)
		if prompt == "" {
			return nil, fmt.Errorf("ai.extract_page: prompt is required for natural extract_mode")
		}

		// Clean HTML for the LLM.
		cleaned, cleanErr := CleanContent(fetchResult.HTML, pageURL, CleanOptions{})
		if cleanErr != nil {
			return nil, fmt.Errorf("ai.extract_page: clean: %w", cleanErr)
		}

		domain := domainFromURL(pageURL)
		hash := shortHash(prompt)
		configName := fmt.Sprintf("extract_%s_%s", domain, hash)
		schema := map[string]interface{}{
			"type":        "object",
			"description": prompt,
		}

		generated, genErr := n.CfgClient.GenerateConfig(ctx, configName, cleaned.Markdown, prompt, schema)
		if genErr != nil {
			// Fallback: return cleaned markdown as extracted content.
			out := workflow.NewItem(map[string]interface{}{
				"url":            pageURL,
				"extracted":      cleaned.Markdown,
				"selectors_used": map[string]string{},
				"extract_mode":   extractMode,
				"fetch_time_ms":  fetchMs,
				"error":          fmt.Sprintf("AI generation failed, returning markdown fallback: %v", genErr),
			})
			return []workflow.NodeOutput{{Handle: "main", Items: []workflow.Item{out}}}, nil
		}

		selectors, err = configToSelectors(generated)
		if err != nil {
			return nil, fmt.Errorf("ai.extract_page: parse generated selectors: %w", err)
		}

		// If the API returned a list_selector and none was set, use it.
		if listSelector == "" {
			if ls, ok := generated["list_selector"].(string); ok {
				listSelector = ls
			}
		}

	default:
		return nil, fmt.Errorf("ai.extract_page: unknown extract_mode %q", extractMode)
	}

	// --- apply selectors ---
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(fetchResult.HTML))
	if err != nil {
		return nil, fmt.Errorf("ai.extract_page: parse HTML: %w", err)
	}

	if listSelector != "" {
		// List extraction: iterate over matching elements.
		var results []interface{}
		doc.Find(listSelector).Each(func(_ int, s *goquery.Selection) {
			row := extractFields(s, selectors)
			results = append(results, row)
		})

		out := workflow.NewItem(map[string]interface{}{
			"url":            pageURL,
			"extracted":      results,
			"selectors_used": selectors,
			"extract_mode":   extractMode,
			"fetch_time_ms":  fetchMs,
			"count":          len(results),
			"list_selector":  listSelector,
		})
		return []workflow.NodeOutput{{Handle: "main", Items: []workflow.Item{out}}}, nil
	}

	// Single-object extraction from the whole document.
	extracted := extractFields(doc.Selection, selectors)

	out := workflow.NewItem(map[string]interface{}{
		"url":            pageURL,
		"extracted":      extracted,
		"selectors_used": selectors,
		"extract_mode":   extractMode,
		"fetch_time_ms":  fetchMs,
	})
	return []workflow.NodeOutput{{Handle: "main", Items: []workflow.Item{out}}}, nil
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// parseFieldsConfig extracts the fields map from config. It accepts either a
// JSON string or a map[string]interface{} with string values.
func parseFieldsConfig(config map[string]interface{}) (map[string]string, error) {
	raw, ok := config["fields"]
	if !ok {
		return nil, fmt.Errorf("fields config is required for css extract_mode")
	}

	switch v := raw.(type) {
	case string:
		var m map[string]string
		if err := json.Unmarshal([]byte(v), &m); err != nil {
			return nil, fmt.Errorf("parse fields JSON: %w", err)
		}
		return m, nil
	case map[string]interface{}:
		m := make(map[string]string, len(v))
		for k, val := range v {
			s, ok := val.(string)
			if !ok {
				return nil, fmt.Errorf("fields[%q] must be a string selector, got %T", k, val)
			}
			m[k] = s
		}
		return m, nil
	default:
		return nil, fmt.Errorf("fields must be a JSON string or object, got %T", raw)
	}
}

// extractFields applies a selector map to a goquery selection.
// Supports @attr suffix: "img.hero@src" extracts the src attribute of img.hero.
func extractFields(root *goquery.Selection, selectors map[string]string) map[string]interface{} {
	result := make(map[string]interface{}, len(selectors))
	for name, sel := range selectors {
		cssSelector, attr := splitAttr(sel)
		el := root.Find(cssSelector).First()
		if el.Length() == 0 {
			result[name] = ""
			continue
		}
		if attr != "" {
			val, _ := el.Attr(attr)
			result[name] = val
		} else {
			result[name] = strings.TrimSpace(el.Text())
		}
	}
	return result
}

// splitAttr splits "selector@attr" into ("selector", "attr").
// If no @ is present, attr is empty.
func splitAttr(s string) (selector, attr string) {
	idx := strings.LastIndex(s, "@")
	if idx < 0 {
		return s, ""
	}
	return s[:idx], s[idx+1:]
}

// configToSelectors converts a map[string]interface{} (from the API) into
// map[string]string, keeping only string-valued entries.
func configToSelectors(m map[string]interface{}) (map[string]string, error) {
	result := make(map[string]string, len(m))
	for k, v := range m {
		if k == "list_selector" {
			continue // handled separately
		}
		s, ok := v.(string)
		if !ok {
			continue // skip non-string entries (e.g. nested objects)
		}
		result[k] = s
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("generated config contained no usable selectors")
	}
	return result, nil
}

// domainFromURL extracts the hostname from a URL, replacing dots with
// underscores for safe config naming.
func domainFromURL(rawURL string) string {
	u, err := url.Parse(rawURL)
	if err != nil || u.Host == "" {
		return "unknown"
	}
	return strings.ReplaceAll(u.Hostname(), ".", "_")
}

// shortHash returns the first 8 hex chars of the SHA-256 of s.
func shortHash(s string) string {
	h := sha256.Sum256([]byte(s))
	return fmt.Sprintf("%x", h[:4])
}
