package crawl

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
	cfgpkg "github.com/monoes/mono-agent/internal/config"
	"github.com/monoes/mono-agent/internal/workflow"
)

// ConfigGenerator produces an extraction config for a page. It is satisfied
// by *config.AgentGenerator, whose GenerateConfig returns
// {"config_name": "...", "fields": {"<field>": {"xpath": "...", ...}}}.
type ConfigGenerator interface {
	GenerateConfig(ctx context.Context, baseName, htmlContent, purpose string, schema map[string]interface{}) (map[string]interface{}, error)
}

var _ ConfigGenerator = (*cfgpkg.AgentGenerator)(nil)

// ExtractPageNode implements the ai.extract_page workflow node.
// It fetches a web page and extracts structured data using CSS selectors
// (provided directly or generated by a locally-installed AI agent).
type ExtractPageNode struct {
	Generator ConfigGenerator
}

func (n *ExtractPageNode) Type() string { return "ai.extract_page" }

func (n *ExtractPageNode) Execute(ctx context.Context, input workflow.NodeInput, config map[string]interface{}) ([]workflow.NodeOutput, error) {
	// --- resolve URL ---
	pageURL, _ := config["url"].(string)
	if pageURL == "" && len(input.Items) > 0 {
		pageURL, _ = input.Items[0].JSON["url"].(string)
	}
	if pageURL == "" {
		return nil, fmt.Errorf("ai.extract_page: url is required (set in config or input item)")
	}

	extractMode, _ := config["extract_mode"].(string)
	if extractMode == "" {
		extractMode = "natural"
	}

	renderMode, _ := config["render_mode"].(string)
	waitSelector, _ := config["wait_selector"].(string)

	// --- fetch ---
	start := time.Now()
	fetchResult, err := FetchPage(ctx, pageURL, FetchOptions{
		RenderMode:   renderMode,
		WaitSelector: waitSelector,
	})
	if err != nil {
		return nil, fmt.Errorf("ai.extract_page: fetch: %w", err)
	}
	fetchMs := time.Since(start).Milliseconds()

	// --- determine selectors ---
	var selectors map[string]string
	listSelector, _ := config["list_selector"].(string)

	switch extractMode {
	case "css":
		selectors, err = parseFieldsConfig(config)
		if err != nil {
			return nil, fmt.Errorf("ai.extract_page: %w", err)
		}

	case "natural":
		if n.Generator == nil {
			return nil, fmt.Errorf("ai.extract_page: AI extraction requires a local agent generator (monomind)")
		}

		prompt, _ := config["prompt"].(string)
		if prompt == "" {
			return nil, fmt.Errorf("ai.extract_page: prompt is required for natural extract_mode")
		}

		domain := domainFromURL(pageURL)
		hash := shortHash(prompt)
		configName := fmt.Sprintf("extract_%s_%s", domain, hash)
		schema := map[string]interface{}{
			"type":        "object",
			"description": prompt,
		}

		// The selectors are generated against the DOM, so the agent gets
		// the page markup (minus scripts and styles), not its markdown.
		generated, genErr := n.Generator.GenerateConfig(ctx, configName, selectorHTML(fetchResult.HTML), naturalPurpose(prompt), schema)
		if genErr != nil {
			return markdownFallback(fetchResult.HTML, pageURL, extractMode, fetchMs,
				fmt.Sprintf("AI generation failed, returning markdown fallback: %v", genErr))
		}

		selectors, err = configToSelectors(generated)
		if err != nil {
			return markdownFallback(fetchResult.HTML, pageURL, extractMode, fetchMs,
				fmt.Sprintf("%v, returning markdown fallback", err))
		}

		// If the agent returned a list_selector and none was set, use it.
		if listSelector == "" {
			if ls, ok := generated["list_selector"].(string); ok {
				listSelector = strings.TrimSpace(ls)
			}
		}

	default:
		return nil, fmt.Errorf("ai.extract_page: unknown extract_mode %q", extractMode)
	}

	// --- apply selectors ---
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(fetchResult.HTML))
	if err != nil {
		return nil, fmt.Errorf("ai.extract_page: parse HTML: %w", err)
	}

	if listSelector != "" {
		// List extraction: iterate over matching elements.
		var results []interface{}
		doc.Find(listSelector).Each(func(_ int, s *goquery.Selection) {
			row := extractFields(s, selectors)
			results = append(results, row)
		})

		out := workflow.NewItem(map[string]interface{}{
			"url":            pageURL,
			"extracted":      results,
			"selectors_used": selectors,
			"extract_mode":   extractMode,
			"fetch_time_ms":  fetchMs,
			"count":          len(results),
			"list_selector":  listSelector,
		})
		return []workflow.NodeOutput{{Handle: "main", Items: []workflow.Item{out}}}, nil
	}

	// Single-object extraction from the whole document.
	extracted := extractFields(doc.Selection, selectors)

	out := workflow.NewItem(map[string]interface{}{
		"url":            pageURL,
		"extracted":      extracted,
		"selectors_used": selectors,
		"extract_mode":   extractMode,
		"fetch_time_ms":  fetchMs,
	})
	return []workflow.NodeOutput{{Handle: "main", Items: []workflow.Item{out}}}, nil
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// parseFieldsConfig extracts the fields map from config. It accepts either a
// JSON string or a map[string]interface{} with string values.
func parseFieldsConfig(config map[string]interface{}) (map[string]string, error) {
	raw, ok := config["fields"]
	if !ok {
		return nil, fmt.Errorf("fields config is required for css extract_mode")
	}

	switch v := raw.(type) {
	case string:
		var m map[string]string
		if err := json.Unmarshal([]byte(v), &m); err != nil {
			return nil, fmt.Errorf("parse fields JSON: %w", err)
		}
		return m, nil
	case map[string]interface{}:
		m := make(map[string]string, len(v))
		for k, val := range v {
			s, ok := val.(string)
			if !ok {
				return nil, fmt.Errorf("fields[%q] must be a string selector, got %T", k, val)
			}
			m[k] = s
		}
		return m, nil
	default:
		return nil, fmt.Errorf("fields must be a JSON string or object, got %T", raw)
	}
}

// extractFields applies a selector map to a goquery selection.
// Supports @attr suffix: "img.hero@src" extracts the src attribute of img.hero.
func extractFields(root *goquery.Selection, selectors map[string]string) map[string]interface{} {
	result := make(map[string]interface{}, len(selectors))
	for name, sel := range selectors {
		cssSelector, attr := splitAttr(sel)
		el := root.Find(cssSelector).First()
		if el.Length() == 0 {
			result[name] = ""
			continue
		}
		if attr != "" {
			val, _ := el.Attr(attr)
			result[name] = val
		} else {
			result[name] = strings.TrimSpace(el.Text())
		}
	}
	return result
}

// splitAttr splits "selector@attr" into ("selector", "attr").
// If no @ is present, attr is empty.
func splitAttr(s string) (selector, attr string) {
	idx := strings.LastIndex(s, "@")
	if idx < 0 {
		return s, ""
	}
	return s[:idx], s[idx+1:]
}

// naturalPurpose wraps the user's prompt with the constraints of this
// node's extractor, which the generic config-generation prompt doesn't know.
func naturalPurpose(prompt string) string {
	return prompt + "\n\n" +
		`Selectors are applied as CSS selectors (goquery), never XPath: put a CSS selector in each field's "xpath" key, ` +
		`appending @attr to read an attribute (e.g. img.hero@src). If the request is for a repeated list of items, ` +
		`also return a top-level "list_selector" (CSS) matching each item, and make the field selectors relative to that item.`
}

// selectorHTML strips the parts of a page that carry no selectable content,
// so the generator's HTML budget is spent on the DOM.
func selectorHTML(rawHTML string) string {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(rawHTML))
	if err != nil {
		return rawHTML
	}
	doc.Find("script, style, noscript, template, svg, link, meta").Remove()
	out, err := doc.Html()
	if err != nil {
		return rawHTML
	}
	return out
}

// markdownFallback is natural mode's documented fallback: when no usable
// selectors can be generated, the node returns the page as markdown along
// with the reason.
func markdownFallback(rawHTML, pageURL, extractMode string, fetchMs int64, reason string) ([]workflow.NodeOutput, error) {
	cleaned, err := CleanContent(rawHTML, pageURL, CleanOptions{})
	if err != nil {
		return nil, fmt.Errorf("ai.extract_page: clean: %w", err)
	}
	out := workflow.NewItem(map[string]interface{}{
		"url":            pageURL,
		"extracted":      cleaned.Markdown,
		"selectors_used": map[string]string{},
		"extract_mode":   extractMode,
		"fetch_time_ms":  fetchMs,
		"error":          reason,
	})
	return []workflow.NodeOutput{{Handle: "main", Items: []workflow.Item{out}}}, nil
}

// configToSelectors turns a generated config, shaped
// {"config_name": "...", "list_selector": "...", "fields": {"<field>": {"xpath": "<css>", "type": "...", "data": ...}}},
// into the same field-name → CSS selector map css mode reads from "fields".
// Only "fields" is read: config_name and list_selector are never selectors.
// A field may also be a bare selector string. Fields without a selector, or
// whose selector is XPath (which goquery can't apply), are skipped.
func configToSelectors(generated map[string]interface{}) (map[string]string, error) {
	fields, _ := generated["fields"].(map[string]interface{})
	result := make(map[string]string, len(fields))
	for name, v := range fields {
		sel := fieldSelector(v)
		if sel == "" || looksLikeXPath(sel) {
			continue
		}
		result[name] = sel
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("generated config contained no usable CSS selectors")
	}
	return result, nil
}

// fieldSelector returns the selector of one generated field.
func fieldSelector(v interface{}) string {
	switch f := v.(type) {
	case string:
		return strings.TrimSpace(f)
	case map[string]interface{}:
		for _, key := range []string{"css", "selector", "xpath"} {
			if s, ok := f[key].(string); ok && strings.TrimSpace(s) != "" {
				return strings.TrimSpace(s)
			}
		}
	}
	return ""
}

// looksLikeXPath reports whether sel is XPath (or an XPath template with
// {FIELD} placeholders) rather than a CSS selector.
func looksLikeXPath(sel string) bool {
	return strings.HasPrefix(sel, "/") || strings.HasPrefix(sel, "./") || strings.HasPrefix(sel, "(") ||
		strings.Contains(sel, "[@") || strings.Contains(sel, "::") || strings.Contains(sel, "()") ||
		strings.Contains(sel, "{")
}

// domainFromURL extracts the hostname from a URL, replacing dots with
// underscores for safe config naming.
func domainFromURL(rawURL string) string {
	u, err := url.Parse(rawURL)
	if err != nil || u.Host == "" {
		return "unknown"
	}
	return strings.ReplaceAll(u.Hostname(), ".", "_")
}

// shortHash returns the first 8 hex chars of the SHA-256 of s.
func shortHash(s string) string {
	h := sha256.Sum256([]byte(s))
	return fmt.Sprintf("%x", h[:4])
}
