package schemagen

// fieldDocs describes fields whose Go declarations carry no comment.
// Keys are "TypeName.jsonName". A struct comment, when one is added later,
// wins over the entry here.
var fieldDocs = map[string]string{
	// automation.json
	"Manifest.$schema":      "Editor schema pointer; ignored at run time.",
	"Manifest.schema":       "Manifest format version.",
	"Manifest.id":           "Package id: lowercase letters, digits and dashes. Workflow nodes are named <id>.<action>.",
	"Manifest.name":         "Display name.",
	"Manifest.version":      "Package version (semver). Installing a lower version than the installed one is refused.",
	"Manifest.description":  "One-line summary shown on the package card.",
	"Manifest.license":      "SPDX license id.",
	"Manifest.category":     "Grouping on the Connections page, e.g. social, ai, crm.",
	"Manifest.site":         "The site the package automates. site.domains is enforced.",
	"Manifest.login":        "How to log in, and how to tell a session is logged in.",
	"Manifest.permissions":  "What the package's actions may do; checked when an action is validated.",
	"Manifest.requires":     "Native bots and fragments the package needs.",
	"Manifest.actions":      "Action names; each is actions/<name>.json.",
	"Manifest.defaults":     "Default step options for the package's actions (e.g. humanLike, timeoutSec).",
	"Manifest.policy":       "Usage-policy tier.",
	"Manifest.publisher":    "Who publishes the package.",
	"Publisher.name":        "Publisher name.",
	"Publisher.url":         "Publisher web page.",
	"Site.startUrl":         "Page a new session opens; available to steps as {{site.startUrl}}.",
	"Site.domains":          "Hosts steps may navigate to: exact hosts or \"*.example.com\" (which also matches example.com). Anything else fails with off_domain.",
	"Login.url":             "Page the login command opens.",
	"Login.loggedIn":        "Signal that the session is logged in.",
	"Login.usernameFrom":    "Where the logged-in username is read from.",
	"Login.sessionTtlDays":  "Days a captured session is assumed valid.",
	"Probe.selector":        "CSS selector (a comma list means any of them) present only when logged in.",
	"Probe.cookie":          "Name of a cookie present only when logged in.",
	"AttrProbe.selector":    "CSS selector of the element holding the username.",
	"Permissions.downloads": "Whether download steps are allowed.",
	"Requires.fragments":    "Fragments from other packages this package calls.",

	// actions/<name>.json
	"ActionDef.actionType":    "Action name; must equal the file name without .json.",
	"ActionDef.platform":      "Legacy owning platform (upper case). New actions set automation instead.",
	"ActionDef.version":       "Action version (semver).",
	"ActionDef.description":   "What the action does, in one or two sentences.",
	"ActionDef.metadata":      "Free-form flags, e.g. requiresAuth, supportsPagination, supportsRetry.",
	"ActionDef.inputs":        "Inputs; the workflow node form is generated from them.",
	"ActionDef.outputs":       "Output field names by outcome, e.g. {\"success\": [\"url\"], \"failure\": [\"error\"]}.",
	"ActionDef.steps":         "Steps, run in order. Steps named by a condition's then/else or a loop run only from there.",
	"ActionDef.loops":         "Id-based loops over a list variable (for_each is the inline alternative).",
	"ActionDef.errorHandling": "Action-wide retry policy.",

	"StepDef.id":            "Step id, unique within the action.",
	"StepDef.type":          "Step type.",
	"StepDef.url":           "navigate: target URL (template). Must be inside site.domains.",
	"StepDef.selector":      "CSS selector of the target element.",
	"StepDef.xpath":         "XPath of the target element (tried before selector).",
	"StepDef.configKey":     "Name of a selectors.json entry (tried after xpath and selector).",
	"StepDef.alternatives":  "Fallback CSS selectors tried in order.",
	"StepDef.elementRef":    "Variable holding an element found by an earlier step (a find_element step id or variable_name).",
	"StepDef.value":         "Value to type or set (template).",
	"StepDef.text":          "Text to type (template), or text to match.",
	"StepDef.attribute":     "extract_attribute: attribute name.",
	"StepDef.direction":     "scroll: up or down.",
	"StepDef.duration":      "wait: seconds (number or template).",
	"StepDef.timeout":       "Seconds before the step fails.",
	"StepDef.humanLike":     "Type and move like a person (jittered delays).",
	"StepDef.methodName":    "call_bot_method: native bot method name.",
	"StepDef.method":        "call_bot_method: alias of methodName.",
	"StepDef.args":          "call_bot_method: arguments (templates).",
	"StepDef.variable":      "Variable the step reads or writes.",
	"StepDef.variable_name": "Variable the step's result is stored in.",
	"StepDef.waitFor":       "CSS selector to wait for before the step runs.",
	"StepDef.waitAfter":     "Seconds to wait after the step.",
	"StepDef.raceSelectors": "find_element: label → selector; the first present wins and its label is stored.",
	"StepDef.condition":     "condition: a ConditionDef object or an expression string.",
	"StepDef.then":          "condition: step ids to run when true.",
	"StepDef.else":          "condition: step ids to run when false.",
	"StepDef.onError":       "What to do when the step fails.",
	"StepDef.onSuccess":     "What to do when the step succeeds.",
	"StepDef.set":           "set_variable: variable → value (templates).",
	"StepDef.description":   "Human note; shown in logs.",
	"StepDef.dataSource":    "save_data / update_progress: variable holding the data.",
	"StepDef.batchSize":     "save_data: items per batch.",
	"StepDef.increment":     "update_progress: counter variable to increment.",
	"StepDef.as":            "for_each: name of the item variable (default \"item\").",
	"StepDef.steps":         "for_each: the loop body.",
	"StepDef.ops":           "transform: operations, applied in order.",

	"LoopDef.id":       "Loop id.",
	"LoopDef.iterator": "Variable holding the list to iterate.",
	"LoopDef.indexVar": "Variable holding the current index.",
	"LoopDef.steps":    "Step ids run for each item.",
	"LoopDef.maxItems": "Per-run cap (template).",

	"ConditionDef.variable": "Variable to test.",
	"ConditionDef.value":    "Value to compare with.",

	"ErrorHandlerDef.action":     "What to do when the step fails.",
	"ErrorHandlerDef.maxRetries": "retry: attempts before onFailure applies.",
	"ErrorHandlerDef.onFailure":  "Action after the retries are used up.",

	"GlobalErrorConfig.globalRetries":  "Retries of the whole action.",
	"GlobalErrorConfig.retryDelay":     "Seconds between retries.",
	"GlobalErrorConfig.onFinalFailure": "What to do after the last retry fails.",

	"SuccessAction.variable":  "Variable to set.",
	"SuccessAction.value":     "Value to set.",
	"SuccessAction.increment": "Counter variable to increment.",

	"TransformOp.op":      "Operation.",
	"TransformOp.field":   "Field the operation reads (tree_parent: the depth field).",
	"TransformOp.to":      "Field the result is written to (default: field).",
	"TransformOp.pattern": "regex_extract / replace: Go regular expression.",
	"TransformOp.layout":  "parse_date: Go time layout, or \"auto\".",
	"TransformOp.sep":     "join / split: separator.",
	"TransformOp.where":   "filter / flag: condition evaluated against each item.",
	"TransformOp.map":     "map: new field → template over the item.",
	"TransformOp.fields":  "pick: keys to keep.",
	"TransformOp.count":   "limit: items to keep.",

	"WaitSpec.networkIdle": "No network requests for a short while.",
	"WaitSpec.any":         "Any of these conditions (first match wins).",

	// fragments/<name>.json
	"FragmentDef.name":        "Fragment name; must equal the file name without .json.",
	"FragmentDef.description": "What the fragment does.",
	"FragmentDef.inputs":      "Variables the caller passes with call_fragment inputs.",
	"FragmentDef.steps":       "Steps, run in order in the caller's context.",

	// selectors.json
	"SelectorEntry.candidates": "Selectors tried in order; the first that finds the element wins.",
	"SelectorEntry.intent":     "The element in plain words; used by the AI fallback when no candidate matches.",
	"SelectorEntry.verifiedAt": "When the candidates last matched on the live site (RFC 3339).",
	"SelectorCandidate.css":    "CSS selector.",
	"SelectorCandidate.xpath":  "XPath.",
	"SelectorCandidate.aria":   "ARIA role and accessible name; the most layout-stable kind.",
	"SelectorCandidate.score":  "Confidence 0..1 (informational).",
	"AriaSelector.role":        "ARIA role, e.g. button, textbox, link.",
	"AriaSelector.name":        "Accessible name, e.g. the button label.",
}
