package orgdesign

import (
	"encoding/json"
	"reflect"
	"sort"
	"strings"
	"sync"
)

// Org × workflow unification keys (docs/plans/2026-09-15-org-workflow-unification.md
// §6.1, contracts doc §7). Every one is optional and passthrough for
// monomind. Each nested type keeps its own Extra bucket so a key added later
// by monomind or by hand survives a Load→Save cycle, the same guarantee Doc
// and Role already give at their own level.

// Org kinds.
const (
	OrgKindStandard = "standard"
	OrgKindHolding  = "holding"
)

// Role kinds.
const (
	RoleKindAgent    = "agent"
	RoleKindEndpoint = "endpoint"
)

// AutomationRef is one entry of an org's automations[] membership list: a
// workflow that belongs to the org, addressed inside it by Alias.
type AutomationRef struct {
	WorkflowID string `json:"workflow_id"`
	Alias      string `json:"alias"`
	Owned      bool   `json:"owned,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// GrantSpec is one entry of roles[].automations[] — the display copy of a
// grant. Enforcement always reads the org_grants row (internal/orggrant);
// reconcile strips any entry that has no live row.
type GrantSpec struct {
	Alias          string          `json:"alias"`
	Mode           string          `json:"mode,omitempty"` // run | trigger | status
	Wait           *bool           `json:"wait,omitempty"`
	TimeoutSeconds int             `json:"timeout_seconds,omitempty"`
	Approval       string          `json:"approval,omitempty"` // none | required
	InputSchema    json.RawMessage `json:"input_schema,omitempty"`
	MaxCallsPerRun int             `json:"max_calls_per_run,omitempty"`
	MaxCallsPerDay int             `json:"max_calls_per_day,omitempty"`
	MaxOutputBytes int             `json:"max_output_bytes,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// ToolProvider is one entry of roles[].tool_providers[] (monomind M1). The
// entry named ProviderName is generated by mono-agent; any other entry is
// left alone.
type ToolProvider struct {
	Kind      string            `json:"kind"`
	Name      string            `json:"name"`
	Command   string            `json:"command"`
	Args      []string          `json:"args"`
	Env       map[string]string `json:"env,omitempty"`
	Allow     []string          `json:"allow,omitempty"`
	Prefix    string            `json:"prefix,omitempty"`
	TimeoutMS int               `json:"timeout_ms,omitempty"`
	IdleMS    int               `json:"idle_ms,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// ProviderName is the name (and prefix) of the tool provider mono-agent
// generates for granted roles.
const ProviderName = "monoagent"

// Endpoint is an endpoint role's delivery target (monomind M2).
type Endpoint struct {
	URL            string `json:"url"`
	CredentialFile string `json:"credential_file,omitempty"`
	TimeoutMS      int    `json:"timeout_ms,omitempty"`
	InputHint      string `json:"input_hint,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// EndpointAutomation is mono-agent's own half of an automation role: which
// workflow answers messages sent to it, and what it replies with.
type EndpointAutomation struct {
	WorkflowID string `json:"workflow_id"`
	Reply      string `json:"reply,omitempty"` // last_node | node:<name>
	Alias      string `json:"alias,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// ChildOrg is one entry of a holding org's children[].
type ChildOrg struct {
	Org         string   `json:"org"`
	Start       string   `json:"start,omitempty"` // on_demand | with_parent | manual
	BudgetShare *float64 `json:"budget_share,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// Federation is the cross-root messaging policy enforced by monomind M4.
type Federation struct {
	AllowFrom []string `json:"allow_from,omitempty"`
	AllowTo   []string `json:"allow_to,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// Autonomy is the display copy of an org's autonomy settings (plan §7.7).
// The decision service enforces from the org_autonomy row; reconcile only
// ever copies a lower level from here into it.
type Autonomy struct {
	Level            string            `json:"level,omitempty"` // manual | mid | full
	Decider          *Decider          `json:"decider,omitempty"`
	Tiers            map[string]string `json:"tiers,omitempty"`
	Policy           string            `json:"policy,omitempty"`
	OnDeciderFailure string            `json:"on_decider_failure,omitempty"` // deny | human
	Limits           *AutonomyLimits   `json:"limits,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// Decider selects who resolves decisions the level routes away from a rule
// or a human.
type Decider struct {
	Kind           string `json:"kind,omitempty"` // model | boss | parent | jev
	Runtime        string `json:"runtime,omitempty"`
	Model          string `json:"model,omitempty"`
	Fallback       string `json:"fallback,omitempty"`
	TimeoutSeconds int    `json:"timeout_seconds,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

// AutonomyLimits caps decider use per org run.
type AutonomyLimits struct {
	MaxDecisionsPerRun  int     `json:"max_decisions_per_run,omitempty"`
	MaxDeciderUSDPerRun float64 `json:"max_decider_usd_per_run,omitempty"`

	Extra map[string]json.RawMessage `json:"-"`
}

func (v *AutomationRef) UnmarshalJSON(b []byte) error {
	type alias AutomationRef
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v AutomationRef) MarshalJSON() ([]byte, error) {
	type alias AutomationRef
	return encodePassthrough(alias(v), v.Extra)
}

func (v *GrantSpec) UnmarshalJSON(b []byte) error {
	type alias GrantSpec
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v GrantSpec) MarshalJSON() ([]byte, error) {
	type alias GrantSpec
	return encodePassthrough(alias(v), v.Extra)
}

func (v *ToolProvider) UnmarshalJSON(b []byte) error {
	type alias ToolProvider
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v ToolProvider) MarshalJSON() ([]byte, error) {
	type alias ToolProvider
	if v.Args == nil {
		v.Args = []string{}
	}
	return encodePassthrough(alias(v), v.Extra)
}

func (v *Endpoint) UnmarshalJSON(b []byte) error {
	type alias Endpoint
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v Endpoint) MarshalJSON() ([]byte, error) {
	type alias Endpoint
	return encodePassthrough(alias(v), v.Extra)
}

func (v *EndpointAutomation) UnmarshalJSON(b []byte) error {
	type alias EndpointAutomation
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v EndpointAutomation) MarshalJSON() ([]byte, error) {
	type alias EndpointAutomation
	return encodePassthrough(alias(v), v.Extra)
}

func (v *ChildOrg) UnmarshalJSON(b []byte) error {
	type alias ChildOrg
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v ChildOrg) MarshalJSON() ([]byte, error) {
	type alias ChildOrg
	return encodePassthrough(alias(v), v.Extra)
}

func (v *Federation) UnmarshalJSON(b []byte) error {
	type alias Federation
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v Federation) MarshalJSON() ([]byte, error) {
	type alias Federation
	return encodePassthrough(alias(v), v.Extra)
}

func (v *Autonomy) UnmarshalJSON(b []byte) error {
	type alias Autonomy
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v Autonomy) MarshalJSON() ([]byte, error) {
	type alias Autonomy
	return encodePassthrough(alias(v), v.Extra)
}

func (v *Decider) UnmarshalJSON(b []byte) error {
	type alias Decider
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v Decider) MarshalJSON() ([]byte, error) {
	type alias Decider
	return encodePassthrough(alias(v), v.Extra)
}

func (v *AutonomyLimits) UnmarshalJSON(b []byte) error {
	type alias AutonomyLimits
	return decodePassthrough(b, (*alias)(v), &v.Extra)
}
func (v AutonomyLimits) MarshalJSON() ([]byte, error) {
	type alias AutonomyLimits
	return encodePassthrough(alias(v), v.Extra)
}

// decodePassthrough decodes b into dst (a pointer to a struct alias with no
// custom methods) and stores every key dst's json tags don't name into
// *extra.
func decodePassthrough(b []byte, dst interface{}, extra *map[string]json.RawMessage) error {
	if err := json.Unmarshal(b, dst); err != nil {
		return err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	known := jsonKeysOf(reflect.TypeOf(dst).Elem())
	out := map[string]json.RawMessage{}
	for k, val := range raw {
		if !known[k] {
			out[k] = val
		}
	}
	if len(out) == 0 {
		out = nil
	}
	*extra = out
	return nil
}

// encodePassthrough marshals v (a struct alias) and merges extra back in.
// With no extra keys the output keeps field declaration order; otherwise
// keys are sorted, as Doc and Role already do.
func encodePassthrough(v interface{}, extra map[string]json.RawMessage) ([]byte, error) {
	base, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	if len(extra) == 0 {
		return base, nil
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(base, &m); err != nil {
		return nil, err
	}
	for k, val := range extra {
		if _, modeled := m[k]; modeled {
			continue
		}
		m[k] = val
	}
	return marshalOrderedMap(m)
}

var jsonKeysCache sync.Map // reflect.Type -> map[string]bool

// jsonKeysOf returns the JSON key names t's exported fields map to.
func jsonKeysOf(t reflect.Type) map[string]bool {
	if cached, ok := jsonKeysCache.Load(t); ok {
		return cached.(map[string]bool)
	}
	keys := map[string]bool{}
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue
		}
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name := strings.Split(tag, ",")[0]
		if name == "" {
			name = f.Name
		}
		keys[name] = true
	}
	jsonKeysCache.Store(t, keys)
	return keys
}

// ─── Role helpers ────────────────────────────────────────────────────────

// IsEndpoint reports whether r is an endpoint (automation) role.
func (r *Role) IsEndpoint() bool { return r.Kind == RoleKindEndpoint }

// IsHolding reports whether d is a holding org.
func (d *Doc) IsHolding() bool { return d.Kind == OrgKindHolding }

// FindAutomation returns the membership entry with alias, or nil.
func (d *Doc) FindAutomation(alias string) *AutomationRef {
	for i := range d.Automations {
		if d.Automations[i].Alias == alias {
			return &d.Automations[i]
		}
	}
	return nil
}

// FindGrantSpec returns r's display grant for alias, or nil.
func (r *Role) FindGrantSpec(alias string) *GrantSpec {
	for i := range r.Automations {
		if r.Automations[i].Alias == alias {
			return &r.Automations[i]
		}
	}
	return nil
}

// Policy returns a copy of r's policy object's keys (Extra["policy"]), or
// an empty map when the role has none or it isn't an object.
func (r *Role) Policy() map[string]json.RawMessage {
	out := map[string]json.RawMessage{}
	if raw, ok := r.Extra["policy"]; ok {
		_ = json.Unmarshal(raw, &out)
		if out == nil {
			out = map[string]json.RawMessage{}
		}
	}
	return out
}

// SetPolicy writes p back as r's policy object; an empty map removes it.
func (r *Role) SetPolicy(p map[string]json.RawMessage) {
	if len(p) == 0 {
		delete(r.Extra, "policy")
		return
	}
	b, err := marshalOrderedMap(p)
	if err != nil {
		return
	}
	if r.Extra == nil {
		r.Extra = map[string]json.RawMessage{}
	}
	r.Extra["policy"] = b
}

// PolicyStrings returns policy[key] as a string list (nil when absent or not
// a string array).
func (r *Role) PolicyStrings(key string) []string {
	raw, ok := r.Policy()[key]
	if !ok {
		return nil
	}
	var out []string
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil
	}
	return out
}

// SetPolicyStrings sets policy[key] to vals (sorted, de-duplicated); an
// empty vals removes the key.
func (r *Role) SetPolicyStrings(key string, vals []string) {
	p := r.Policy()
	vals = sortedUnique(vals)
	if len(vals) == 0 {
		delete(p, key)
	} else {
		b, _ := json.Marshal(vals)
		p[key] = b
	}
	r.SetPolicy(p)
}

func sortedUnique(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}
