// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActionTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddActionTarget'](arg1, arg2, arg3);
}

export function AddPersonMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddPersonMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddPersonStatus(arg1, arg2) {
  return window['go']['main']['App']['AddPersonStatus'](arg1, arg2);
}

export function AddPersonTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPersonTag'](arg1, arg2, arg3);
}

export function AddSecret(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddSecret'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddVaultImage(arg1, arg2) {
  return window['go']['main']['App']['AddVaultImage'](arg1, arg2);
}

export function AnswerOrgQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerOrgQuestion'](arg1, arg2, arg3);
}

export function AppSelfUpdate() {
  return window['go']['main']['App']['AppSelfUpdate']();
}

export function ApproveHIL(arg1, arg2) {
  return window['go']['main']['App']['ApproveHIL'](arg1, arg2);
}

export function ApproveOrgAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApproveOrgAction'](arg1, arg2, arg3);
}

export function CancelWorkflow(arg1) {
  return window['go']['main']['App']['CancelWorkflow'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearAIChatHistory(arg1) {
  return window['go']['main']['App']['ClearAIChatHistory'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ComposePersonMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ComposePersonMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function ConfirmSocialLogin(arg1) {
  return window['go']['main']['App']['ConfirmSocialLogin'](arg1);
}

export function ConnectPlatformOAuth(arg1) {
  return window['go']['main']['App']['ConnectPlatformOAuth'](arg1);
}

export function CreateAction(arg1) {
  return window['go']['main']['App']['CreateAction'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateResource'](arg1, arg2, arg3, arg4);
}

export function CreateWorkflowFromTemplate(arg1) {
  return window['go']['main']['App']['CreateWorkflowFromTemplate'](arg1);
}

export function DeleteAIProvider(arg1) {
  return window['go']['main']['App']['DeleteAIProvider'](arg1);
}

export function DeleteAction(arg1) {
  return window['go']['main']['App']['DeleteAction'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteVaultImage(arg1) {
  return window['go']['main']['App']['DeleteVaultImage'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function DenyOrgAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['DenyOrgAction'](arg1, arg2, arg3);
}

export function ExecuteAction(arg1) {
  return window['go']['main']['App']['ExecuteAction'](arg1);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function ExportVaultAll() {
  return window['go']['main']['App']['ExportVaultAll']();
}

export function GateApproveOrgAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['GateApproveOrgAction'](arg1, arg2, arg3);
}

export function GateRejectOrgAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['GateRejectOrgAction'](arg1, arg2, arg3);
}

export function GetAIChatHistory(arg1) {
  return window['go']['main']['App']['GetAIChatHistory'](arg1);
}

export function GetAIModels(arg1) {
  return window['go']['main']['App']['GetAIModels'](arg1);
}

export function GetAIRegistry() {
  return window['go']['main']['App']['GetAIRegistry']();
}

export function GetAction(arg1) {
  return window['go']['main']['App']['GetAction'](arg1);
}

export function GetActionTargets(arg1) {
  return window['go']['main']['App']['GetActionTargets'](arg1);
}

export function GetActions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetActions'](arg1, arg2, arg3);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetAllPersonMessages(arg1) {
  return window['go']['main']['App']['GetAllPersonMessages'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAvailableActionTypes() {
  return window['go']['main']['App']['GetAvailableActionTypes']();
}

export function GetConnectionsForPlatform(arg1) {
  return window['go']['main']['App']['GetConnectionsForPlatform'](arg1);
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDraftPersonMessages() {
  return window['go']['main']['App']['GetDraftPersonMessages']();
}

export function GetExecutionDetail(arg1) {
  return window['go']['main']['App']['GetExecutionDetail'](arg1);
}

export function GetHILItems() {
  return window['go']['main']['App']['GetHILItems']();
}

export function GetLatestPersonStatus(arg1) {
  return window['go']['main']['App']['GetLatestPersonStatus'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOAuthCredentials(arg1) {
  return window['go']['main']['App']['GetOAuthCredentials'](arg1);
}

export function GetOrgCosts(arg1) {
  return window['go']['main']['App']['GetOrgCosts'](arg1);
}

export function GetOrgDecisions(arg1) {
  return window['go']['main']['App']['GetOrgDecisions'](arg1);
}

export function GetOrgFlow(arg1) {
  return window['go']['main']['App']['GetOrgFlow'](arg1);
}

export function GetOrgGates(arg1) {
  return window['go']['main']['App']['GetOrgGates'](arg1);
}

export function GetOrgLogs(arg1) {
  return window['go']['main']['App']['GetOrgLogs'](arg1);
}

export function GetOrgMemoryStats(arg1) {
  return window['go']['main']['App']['GetOrgMemoryStats'](arg1);
}

export function GetOrgQuestions(arg1) {
  return window['go']['main']['App']['GetOrgQuestions'](arg1);
}

export function GetOrgReport(arg1, arg2) {
  return window['go']['main']['App']['GetOrgReport'](arg1, arg2);
}

export function GetOrgStatus(arg1) {
  return window['go']['main']['App']['GetOrgStatus'](arg1);
}

export function GetPeople(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPeople'](arg1, arg2, arg3, arg4);
}

export function GetPeopleCount(arg1, arg2) {
  return window['go']['main']['App']['GetPeopleCount'](arg1, arg2);
}

export function GetPeopleTagsMap(arg1) {
  return window['go']['main']['App']['GetPeopleTagsMap'](arg1);
}

export function GetPersonDetail(arg1) {
  return window['go']['main']['App']['GetPersonDetail'](arg1);
}

export function GetPersonInteractions(arg1) {
  return window['go']['main']['App']['GetPersonInteractions'](arg1);
}

export function GetPersonMessages(arg1) {
  return window['go']['main']['App']['GetPersonMessages'](arg1);
}

export function GetPersonPosts(arg1) {
  return window['go']['main']['App']['GetPersonPosts'](arg1);
}

export function GetPersonStatusHistory(arg1, arg2) {
  return window['go']['main']['App']['GetPersonStatusHistory'](arg1, arg2);
}

export function GetPersonTags(arg1) {
  return window['go']['main']['App']['GetPersonTags'](arg1);
}

export function GetPostComments(arg1) {
  return window['go']['main']['App']['GetPostComments'](arg1);
}

export function GetPostDetail(arg1) {
  return window['go']['main']['App']['GetPostDetail'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRecentExecutions(arg1) {
  return window['go']['main']['App']['GetRecentExecutions'](arg1);
}

export function GetSecretFields(arg1) {
  return window['go']['main']['App']['GetSecretFields'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSocialLists() {
  return window['go']['main']['App']['GetSocialLists']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetVaultImage(arg1) {
  return window['go']['main']['App']['GetVaultImage'](arg1);
}

export function GetVaultImageData(arg1) {
  return window['go']['main']['App']['GetVaultImageData'](arg1);
}

export function GetVaultImages(arg1) {
  return window['go']['main']['App']['GetVaultImages'](arg1);
}

export function GetVaultStats() {
  return window['go']['main']['App']['GetVaultStats']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkflow(arg1) {
  return window['go']['main']['App']['GetWorkflow'](arg1);
}

export function GetWorkflowExecutions(arg1, arg2) {
  return window['go']['main']['App']['GetWorkflowExecutions'](arg1, arg2);
}

export function GetWorkflowNodeTypes() {
  return window['go']['main']['App']['GetWorkflowNodeTypes']();
}

export function ImportVaultAll(arg1, arg2) {
  return window['go']['main']['App']['ImportVaultAll'](arg1, arg2);
}

export function IsDBConnected() {
  return window['go']['main']['App']['IsDBConnected']();
}

export function ListAIProviders() {
  return window['go']['main']['App']['ListAIProviders']();
}

export function ListConnections(arg1) {
  return window['go']['main']['App']['ListConnections'](arg1);
}

export function ListCredentialsForNode(arg1) {
  return window['go']['main']['App']['ListCredentialsForNode'](arg1);
}

export function ListOrgs() {
  return window['go']['main']['App']['ListOrgs']();
}

export function ListPlatformsJSON(arg1) {
  return window['go']['main']['App']['ListPlatformsJSON'](arg1);
}

export function ListResources(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListResources'](arg1, arg2, arg3, arg4);
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function ListWorkflowTemplates() {
  return window['go']['main']['App']['ListWorkflowTemplates']();
}

export function ListWorkflows() {
  return window['go']['main']['App']['ListWorkflows']();
}

export function LoginSocial(arg1) {
  return window['go']['main']['App']['LoginSocial'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function OpenVaultFilePicker() {
  return window['go']['main']['App']['OpenVaultFilePicker']();
}

export function OpenVaultImportFilePicker() {
  return window['go']['main']['App']['OpenVaultImportFilePicker']();
}

export function RejectDraftPersonMessage(arg1) {
  return window['go']['main']['App']['RejectDraftPersonMessage'](arg1);
}

export function RejectHIL(arg1) {
  return window['go']['main']['App']['RejectHIL'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RemovePersonTag(arg1, arg2) {
  return window['go']['main']['App']['RemovePersonTag'](arg1, arg2);
}

export function RunNode(arg1) {
  return window['go']['main']['App']['RunNode'](arg1);
}

export function RunWorkflow(arg1) {
  return window['go']['main']['App']['RunWorkflow'](arg1);
}

export function SaveAIProvider(arg1) {
  return window['go']['main']['App']['SaveAIProvider'](arg1);
}

export function SaveConnectionDirect(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConnectionDirect'](arg1, arg2, arg3);
}

export function SaveVaultImageToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveVaultImageToFile'](arg1, arg2);
}

export function SaveWorkflow(arg1) {
  return window['go']['main']['App']['SaveWorkflow'](arg1);
}

export function ScanAgentRuntimes() {
  return window['go']['main']['App']['ScanAgentRuntimes']();
}

export function SearchVaultImages(arg1) {
  return window['go']['main']['App']['SearchVaultImages'](arg1);
}

export function SelfUpdate() {
  return window['go']['main']['App']['SelfUpdate']();
}

export function SendDraftPersonMessage(arg1) {
  return window['go']['main']['App']['SendDraftPersonMessage'](arg1);
}

export function SetOAuthCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOAuthCredentials'](arg1, arg2, arg3);
}

export function SetWorkflowActive(arg1, arg2) {
  return window['go']['main']['App']['SetWorkflowActive'](arg1, arg2);
}

export function StopAIChat(arg1) {
  return window['go']['main']['App']['StopAIChat'](arg1);
}

export function StopAgentChat(arg1) {
  return window['go']['main']['App']['StopAgentChat'](arg1);
}

export function StopOrgEvents(arg1) {
  return window['go']['main']['App']['StopOrgEvents'](arg1);
}

export function StreamAIChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StreamAIChat'](arg1, arg2, arg3, arg4);
}

export function StreamAgentChat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StreamAgentChat'](arg1, arg2, arg3, arg4, arg5);
}

export function StreamOrgEvents(arg1) {
  return window['go']['main']['App']['StreamOrgEvents'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TestAIProvider(arg1) {
  return window['go']['main']['App']['TestAIProvider'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestSession(arg1) {
  return window['go']['main']['App']['TestSession'](arg1);
}

export function UpdateActionParams(arg1, arg2) {
  return window['go']['main']['App']['UpdateActionParams'](arg1, arg2);
}

export function UpdateActionState(arg1, arg2) {
  return window['go']['main']['App']['UpdateActionState'](arg1, arg2);
}

export function UpdateSecret(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateSecret'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateVaultImageLabel(arg1, arg2) {
  return window['go']['main']['App']['UpdateVaultImageLabel'](arg1, arg2);
}
