// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';
import {connections} from '../models';
import {workflow} from '../models';

export function APIConfigReset(arg1:boolean,arg2:boolean):Promise<main.APIConfigChange>;

export function APIConfigSet(arg1:Record<string, string>,arg2:boolean,arg3:boolean):Promise<main.APIConfigChange>;

export function APIConfigShow():Promise<main.APIConfigInfo>;

export function APIConfigUnset(arg1:Array<string>,arg2:boolean,arg3:boolean):Promise<main.APIConfigChange>;

export function APIKeyCreate(arg1:string,arg2:boolean):Promise<main.APIKeyCreated>;

export function APIKeyList():Promise<Array<main.APIKey>>;

export function APIKeyRename(arg1:string,arg2:string):Promise<main.APIKey>;

export function APIKeyRevoke(arg1:string):Promise<main.APIKey>;

export function APIKeySetContext(arg1:string,arg2:boolean):Promise<main.APIKey>;

export function APIModels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.APIModelsInfo>;

export function APIStatus():Promise<main.APIStatusInfo>;

export function AccountLogin():Promise<string>;

export function AccountLoginCancel():Promise<string>;

export function AccountLoginEmailSend(arg1:string):Promise<string>;

export function AccountLoginEmailVerify(arg1:string,arg2:string):Promise<string>;

export function AccountLogout():Promise<string>;

export function AccountStatus():Promise<string>;

export function AddApplication(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function AddAutomationRole(arg1:string,arg2:string):Promise<string>;

export function AddOrgAutomation(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddOrgDocumentEdge(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AddOrgRole(arg1:string,arg2:string):Promise<string>;

export function AddOrgRoleToSection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddOrgSection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddPersonMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function AddPersonStatus(arg1:string,arg2:string):Promise<storage.PersonStatusUpdate>;

export function AddPersonTag(arg1:string,arg2:string,arg3:string):Promise<main.TagInfo>;

export function AddSecret(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Record<string, string>):Promise<string>;

export function AddVaultImage(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AgentRoster():Promise<string>;

export function AgentRosterAdd(arg1:string,arg2:string):Promise<string>;

export function AgentRosterAutoRevalidate():Promise<string>;

export function AgentRosterRemove(arg1:string,arg2:string):Promise<string>;

export function AgentValidatePlan(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<string>;

export function AnalyzeRecording(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function AnswerAgentQuestion(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function AnswerOrgChat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AnswerOrgQuestion(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AppSelfUpdate():Promise<main.UpdateResult>;

export function ApplyToApplication(arg1:string,arg2:Record<string, any>,arg3:Record<string, any>):Promise<main.ApplyResult>;

export function ApproveHIL(arg1:string,arg2:string):Promise<void>;

export function ApproveOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ApprovePendingPerson(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function AssignOrgRole(arg1:string,arg2:string,arg3:string):Promise<string>;

export function BindBrowser(arg1:string,arg2:string):Promise<main.BrowserRow>;

export function CancelHealthRun(arg1:string):Promise<string>;

export function CancelWorkflow(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ChooseAutomationExportPath(arg1:string):Promise<string>;

export function ChooseAutomationPackage():Promise<string>;

export function ChooseInstructionsFile():Promise<string>;

export function ChooseProfileFolder():Promise<string>;

export function ChooseWorkflowFile():Promise<string>;

export function ClearLogs():Promise<void>;

export function CoderDisable():Promise<string>;

export function CoderEnable():Promise<string>;

export function CoderSet(arg1:string,arg2:number,arg3:string,arg4:number):Promise<string>;

export function CoderStatus():Promise<string>;

export function CoderStopBackground(arg1:string,arg2:string):Promise<string>;

export function CoderWorkspaceList():Promise<string>;

export function CoderWorkspaceRoot(arg1:string):Promise<string>;

export function ComposePersonMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<storage.PersonMessage>;

export function ConfirmSocialLogin(arg1:string):Promise<string>;

export function ConnectPlatformOAuth(arg1:string):Promise<string>;

export function ControlOrg(arg1:string,arg2:string):Promise<string>;

export function CreateChatConversation(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CreateCoderConversation(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function CreateOrgDesign(arg1:string):Promise<string>;

export function CreateProfile(arg1:string,arg2:string,arg3:string):Promise<main.ProfileInfo>;

export function CreateResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ResourceItemResult>;

export function CreateWorkflowFromTemplate(arg1:string):Promise<main.WorkflowSummary>;

export function DaemonRestart():Promise<main.DaemonRestartResult>;

export function DeleteChatConversation(arg1:string):Promise<string>;

export function DeleteOrgDesign(arg1:string):Promise<string>;

export function DeleteOrgSection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeletePeople(arg1:Array<string>):Promise<void>;

export function DeleteProfileDocument(arg1:string):Promise<void>;

export function DeleteRecording(arg1:string):Promise<string>;

export function DeleteSecret(arg1:string):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DeleteVaultImage(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function DenyOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DisableAutomation(arg1:string):Promise<string>;

export function DismissOrgChat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DoctorAutomations(arg1:string):Promise<string>;

export function EnableAutomation(arg1:string):Promise<string>;

export function EvaluateApplication(arg1:string,arg2:string):Promise<main.FitVerdictInfo>;

export function EvaluatePendingApplications(arg1:string,arg2:number):Promise<main.EvaluateBatchResult>;

export function ExportAction(arg1:string,arg2:string):Promise<string>;

export function ExportAutomation(arg1:string,arg2:string):Promise<string>;

export function ExportData():Promise<main.ExportResult>;

export function ExportVaultAll():Promise<main.VaultExportResult>;

export function ExportWorkflow(arg1:string):Promise<string>;

export function GateApproveOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GateRejectOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetActiveProfile():Promise<main.ProfileInfo>;

export function GetAgentRuntimeModels(arg1:string,arg2:string):Promise<string>;

export function GetAllPersonMessages(arg1:number):Promise<Array<storage.PersonMessageWithPerson>>;

export function GetAllProfilesRecentExecutions(arg1:number):Promise<Array<main.WorkflowExecutionSummary>>;

export function GetAllTags():Promise<Array<main.TagInfo>>;

export function GetApplication(arg1:string):Promise<main.ApplicationDetail>;

export function GetApplications(arg1:string,arg2:string,arg3:string):Promise<Array<main.ApplicationSummary>>;

export function GetBrowsers():Promise<main.BrowsersReport>;

export function GetCaptureView(arg1:string):Promise<main.CaptureView>;

export function GetChatEvents(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function GetChatTurns(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetConnectionsForPlatform(arg1:string):Promise<Array<connections.SafeConnection>>;

export function GetDBPath():Promise<string>;

export function GetDaemonStatus():Promise<string>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetDraftPersonMessages():Promise<Array<storage.PersonMessageWithPerson>>;

export function GetEffectiveTools(arg1:string,arg2:string):Promise<string>;

export function GetExecutionDetail(arg1:string):Promise<Record<string, any>>;

export function GetGlobalOrgSummary(arg1:boolean):Promise<string>;

export function GetGlobalSummary():Promise<string>;

export function GetHILItems():Promise<Array<main.HILItem>>;

export function GetLatestPersonStatus(arg1:string):Promise<storage.PersonStatusUpdate>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetOAuthCredentials(arg1:string):Promise<string>;

export function GetOrgApprovals(arg1:string):Promise<string>;

export function GetOrgAutonomy(arg1:string):Promise<string>;

export function GetOrgBudget(arg1:string,arg2:string):Promise<string>;

export function GetOrgChatHistory(arg1:string,arg2:string):Promise<string>;

export function GetOrgCosts(arg1:string,arg2:string):Promise<string>;

export function GetOrgDecisions(arg1:string,arg2:string):Promise<string>;

export function GetOrgDocuments(arg1:string,arg2:string):Promise<string>;

export function GetOrgDesign(arg1:string):Promise<string>;

export function GetOrgEstimate(arg1:string):Promise<string>;

export function GetOrgFlow(arg1:string,arg2:string):Promise<string>;

export function GetOrgGates(arg1:string):Promise<string>;

export function GetOrgLogs(arg1:string,arg2:string):Promise<string>;

export function GetOrgMemoryStats(arg1:string):Promise<string>;

export function GetOrgQuestions(arg1:string):Promise<string>;

export function GetOrgReport(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function GetOrgScheduleAudit(arg1:string):Promise<string>;

export function GetOrgStatus(arg1:string):Promise<string>;

export function GetOrgSummary(arg1:boolean):Promise<string>;

export function GetPendingPeopleApprovals():Promise<Array<main.PendingPersonApproval>>;

export function GetPeople(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.PersonInfo>>;

export function GetPeopleCount(arg1:string,arg2:string):Promise<number>;

export function GetPeopleTagsMap(arg1:Array<string>):Promise<Record<string, Array<main.TagInfo>>>;

export function GetPersonDetail(arg1:string):Promise<main.PersonDetailInfo>;

export function GetPersonInteractions(arg1:string):Promise<Array<main.PersonInteraction>>;

export function GetPersonMessages(arg1:string):Promise<Array<storage.PersonMessage>>;

export function GetPersonPosts(arg1:string):Promise<Array<main.PostSummary>>;

export function GetPersonStatusHistory(arg1:string,arg2:number):Promise<Array<storage.PersonStatusUpdate>>;

export function GetPersonTags(arg1:string):Promise<Array<main.TagInfo>>;

export function GetPostComments(arg1:string):Promise<Array<main.PostComment>>;

export function GetPostDetail(arg1:string):Promise<main.PostDetail>;

export function GetProfileDocument(arg1:string):Promise<main.ProfileDocument>;

export function GetProfileDocumentData(arg1:string):Promise<string>;

export function GetProfileDocumentText(arg1:string):Promise<string>;

export function GetProfiles():Promise<Array<main.ProfileInfo>>;

export function GetRecentExecutions(arg1:number):Promise<Array<main.WorkflowExecutionSummary>>;

export function GetSecretFields(arg1:string):Promise<main.VaultFieldsAndNotes>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSocialLists():Promise<Array<main.SocialListInfo>>;

export function GetSummary():Promise<string>;

export function GetSummarySections(arg1:string):Promise<string>;

export function GetTemplates():Promise<Array<main.TemplateInfo>>;

export function GetVaultImage(arg1:string):Promise<Record<string, any>>;

export function GetVaultImageData(arg1:string):Promise<string>;

export function GetVaultImages(arg1:number):Promise<Array<Record<string, any>>>;

export function GetVaultStats():Promise<Record<string, any>>;

export function GetVersion():Promise<main.VersionInfo>;

export function GetWorkflow(arg1:string):Promise<main.WorkflowDetail>;

export function GetWorkflowExecutions(arg1:string,arg2:number):Promise<Array<main.WorkflowExecutionSummary>>;

export function GetWorkflowNodeTypes():Promise<Record<string, any>>;

export function GetWorkflowTriggerInputs(arg1:string):Promise<string>;

export function HasGeneratedDocuments(arg1:string):Promise<boolean>;

export function ImportVaultAll(arg1:string,arg2:string):Promise<main.VaultImportResult>;

export function ImportWorkflow(arg1:string):Promise<main.WorkflowImportResult>;

export function ImportWorkflowFull(arg1:string,arg2:string):Promise<string>;

export function IndexProfileDocument(arg1:string):Promise<main.UploadResult>;

export function InitializeMonomindProfile():Promise<string>;

export function InstallAgentRuntime(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function InstallAutomation(arg1:string,arg2:string):Promise<string>;

export function InstallAutomationDryRun(arg1:string):Promise<string>;

export function IsDBConnected():Promise<boolean>;

export function IsMonomindInitialized():Promise<boolean>;

export function IsReady():Promise<boolean>;

export function JevRemoveKey():Promise<main.JevKeyRemoveResult>;

export function JevSetKey(arg1:string):Promise<main.JevKeySetResult>;

export function JevSetSurface(arg1:string,arg2:boolean,arg3:number):Promise<main.JevSurfaceResult>;

export function JevStatus():Promise<main.JevStatusInfo>;

export function JevTestKey():Promise<main.JevKeyTestResult>;

export function JevUsage(arg1:string):Promise<main.JevUsageReport>;

export function KeyringClearPassphrase():Promise<main.KeyringPassphraseResult>;

export function KeyringSetPassphrase(arg1:string):Promise<main.KeyringPassphraseResult>;

export function KeyringStatus():Promise<main.KeyringStatusInfo>;

export function LibraryInstall(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function LibraryInstalled(arg1:string):Promise<string>;

export function LibraryList(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function LibraryLogin():Promise<string>;

export function LibraryLoginCancel():Promise<string>;

export function LibraryLoginEmailSend(arg1:string):Promise<string>;

export function LibraryLoginEmailVerify(arg1:string,arg2:string):Promise<string>;

export function LibraryLogout():Promise<string>;

export function LibraryPublish(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function LibraryShow(arg1:string):Promise<string>;

export function LibraryStatus(arg1:boolean):Promise<string>;

export function LibraryUpdate(arg1:string):Promise<string>;

export function ListAllProfilesWorkflows():Promise<Array<main.WorkflowSummary>>;

export function ListAutomations():Promise<string>;

export function ListChatConversations(arg1:string,arg2:number):Promise<string>;

export function ListConnections(arg1:string):Promise<Array<connections.SafeConnection>>;

export function ListCredentialsForNode(arg1:string):Promise<Array<main.CredentialOption>>;

export function ListMonomindProjects():Promise<Array<main.MonomindProjectInfo>>;

export function ListNeedsYou(arg1:string):Promise<string>;

export function ListOrgAutomations(arg1:string):Promise<string>;

export function ListOrgDecisionLog(arg1:string,arg2:string):Promise<string>;

export function ListOrgDesigns():Promise<string>;

export function ListOrgGrants(arg1:string):Promise<string>;

export function ListOrgQueuedMessages(arg1:string):Promise<string>;

export function ListOrgs():Promise<string>;

export function ListPlatformsJSON(arg1:string):Promise<string>;

export function ListProfileDocuments():Promise<Array<main.ProfileDocument>>;

export function ListRecordings():Promise<string>;

export function ListResources(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ResourceListResult>;

export function ListSecrets():Promise<Array<main.VaultEntry>>;

export function ListUnassignedAutomations():Promise<string>;

export function ListWorkflowTemplates():Promise<Array<workflow.Template>>;

export function ListWorkflows():Promise<Array<main.WorkflowSummary>>;

export function LoginSocial(arg1:string):Promise<string>;

export function MarkPersonMessageUnread(arg1:string):Promise<void>;

export function MarkPersonMessagesRead(arg1:string,arg2:Array<string>):Promise<void>;

export function MoveProfileFolder(arg1:string,arg2:string):Promise<void>;

export function OpenAnyFilePicker(arg1:string):Promise<string>;

export function OpenJSONFilePicker(arg1:string):Promise<string>;

export function OpenPathWithOS(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenVaultFilePicker():Promise<string>;

export function OpenVaultImportFilePicker():Promise<string>;

export function OrgGroupStatus(arg1:string):Promise<string>;

export function OrgSectionsRuntimes():Promise<string>;

export function OrgRoleSetAccess(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OrgSign(arg1:string,arg2:string):Promise<string>;

export function OrgSignatureReview(arg1:string):Promise<string>;

export function OrgSignatureStatus(arg1:string):Promise<string>;

export function PauseOrgAutonomy(arg1:string,arg2:string):Promise<string>;

export function PickCoderFolder():Promise<string>;

export function PromoteRoleToRoot(arg1:string,arg2:string):Promise<string>;

export function ReadJSONFile(arg1:string):Promise<Record<string, any>>;

export function RejectDraftPersonMessage(arg1:string):Promise<void>;

export function RejectHIL(arg1:string):Promise<void>;

export function RejectPendingPerson(arg1:string):Promise<void>;

export function ReloadOrg(arg1:string):Promise<string>;

export function RemoveAutomationRole(arg1:string,arg2:string):Promise<string>;

export function RemoveConnection(arg1:string):Promise<string>;

export function RemoveOrgAutomation(arg1:string,arg2:string):Promise<string>;

export function RemoveOrgDocumentEdge(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RemoveOrgGrant(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RemoveOrgRole(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RemovePersonTag(arg1:string,arg2:string):Promise<void>;

export function RerecordSelector(arg1:string,arg2:string):Promise<string>;

export function ResolveOrgChat(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<string>;

export function RestoreAutomation(arg1:string):Promise<string>;

export function ResumeOrgAutonomy(arg1:string):Promise<string>;

export function RevealProfileFolder(arg1:string):Promise<void>;

export function RollbackAutomation(arg1:string):Promise<string>;

export function RunHealthCheck(arg1:string):Promise<string>;

export function RunHealthFix(arg1:string):Promise<string>;

export function RunNode(arg1:main.NodeRunRequest):Promise<main.NodeRunResult>;

export function RunOrg(arg1:string,arg2:string):Promise<string>;

export function RunWorkflow(arg1:string):Promise<void>;

export function RunWorkflowWithInput(arg1:string,arg2:string):Promise<void>;

export function SaveConnectionDirect(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveDraft(arg1:string,arg2:string):Promise<string>;

export function SaveOrgDesign(arg1:string,arg2:string):Promise<string>;

export function SaveOrgLayout(arg1:string,arg2:string):Promise<string>;

export function SaveVaultImageToFile(arg1:string,arg2:string):Promise<string>;

export function SaveWorkflow(arg1:main.SaveWorkflowRequest):Promise<main.WorkflowSummary>;

export function ScanAgentRuntimes():Promise<string>;

export function SearchProfileKnowledge(arg1:string):Promise<Array<main.KnowledgeSearchResult>>;

export function SearchVaultImages(arg1:string):Promise<Array<Record<string, any>>>;

export function SendApplication(arg1:string,arg2:string):Promise<void>;

export function SendDraftPersonMessage(arg1:string):Promise<storage.PersonMessage>;

export function SendOrgChat(arg1:string,arg2:string):Promise<string>;

export function SendOrgMessage(arg1:string,arg2:string):Promise<string>;

export function SetAgentRosterAutoRevalidate(arg1:boolean):Promise<string>;

export function SetApplicationStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAutomationTrust(arg1:string,arg2:string):Promise<string>;

export function SetChatOrgMode(arg1:string,arg2:string):Promise<string>;

export function SetOAuthCredentials(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetOrgAutonomy(arg1:string,arg2:string):Promise<string>;

export function SetOrgGrant(arg1:string,arg2:string):Promise<string>;

export function SetOrgRoleReportsTo(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetOrgSchedule(arg1:string,arg2:string):Promise<string>;

export function SetWorkflowActive(arg1:string,arg2:boolean):Promise<void>;

export function ShowAutomation(arg1:string):Promise<string>;

export function ShowRecording(arg1:string):Promise<string>;

export function StartAgentValidation(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<string>;

export function StartChatTurn(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<string>;

export function StartOrgGroup(arg1:string):Promise<string>;

export function StopAgentValidation():Promise<string>;

export function StopChatAgent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopChatTurn(arg1:string,arg2:string):Promise<string>;

export function StopNodeRun(arg1:string):Promise<void>;

export function StopOrgEvents(arg1:string,arg2:string):Promise<string>;

export function StopOrgGroup(arg1:string):Promise<string>;

export function StreamOrgEvents(arg1:string,arg2:string):Promise<string>;

export function SwitchProfile(arg1:string):Promise<void>;

export function TagApplication(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskAdd(arg1:string):Promise<string>;

export function TaskAgentShell():Promise<string>;

export function TaskApprove(arg1:Array<number>,arg2:boolean):Promise<string>;

export function TaskArchive(arg1:Array<number>):Promise<string>;

export function TaskBoard(arg1:number):Promise<string>;

export function TaskComment(arg1:number,arg2:string):Promise<string>;

export function TaskEdit(arg1:number,arg2:string):Promise<string>;

export function TaskMove(arg1:number,arg2:string,arg3:string,arg4:number):Promise<string>;

export function TaskPulse():Promise<Record<string, any>>;

export function TaskShow(arg1:number):Promise<string>;

export function TaskUnarchive(arg1:Array<number>):Promise<string>;

export function TestAutomation(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function TestConnection(arg1:string):Promise<string>;

export function TestSession(arg1:number):Promise<string>;

export function UninstallAutomation(arg1:string):Promise<string>;

export function UpdateOrgRole(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateOrgSection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateSecret(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Record<string, string>):Promise<void>;

export function UpdateTagColor(arg1:string,arg2:string):Promise<boolean>;

export function UpdateVaultImageLabel(arg1:string,arg2:string):Promise<void>;

export function UploadProfileDocument(arg1:string,arg2:string):Promise<main.UploadResult>;

export function ValidateAutomation(arg1:string):Promise<string>;

export function ValidateOrgDesign(arg1:string):Promise<string>;

export function ValidateOrgReport(arg1:string):Promise<string>;

export function VerifyDraft(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function ListPublications(search:string, platform:string, kind:string, workflow:string, agent:string, since:string, until:string, limit:number, offset:number):Promise<string>;
export function GetPublication(id:string):Promise<string>;
export function GetPublicationStats():Promise<string>;
