// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';
import {connections} from '../models';
import {workflow} from '../models';

export function AddActionTarget(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddPersonMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function AddPersonStatus(arg1:string,arg2:string):Promise<storage.PersonStatusUpdate>;

export function AddPersonTag(arg1:string,arg2:string,arg3:string):Promise<main.TagInfo>;

export function AddSecret(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Record<string, string>):Promise<string>;

export function AddVaultImage(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AnswerOrgQuestion(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AppSelfUpdate():Promise<main.UpdateResult>;

export function ApproveHIL(arg1:string,arg2:string):Promise<void>;

export function ApproveOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CancelWorkflow(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearAIChatHistory(arg1:string):Promise<string>;

export function ClearLogs():Promise<void>;

export function ComposePersonMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<storage.PersonMessage>;

export function ConfirmSocialLogin(arg1:string):Promise<string>;

export function ConnectPlatformOAuth(arg1:string):Promise<string>;

export function CreateAction(arg1:main.CreateActionRequest):Promise<main.ActionInfo>;

export function CreateProfile(arg1:string):Promise<main.ProfileInfo>;

export function CreateResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ResourceItemResult>;

export function CreateWorkflowFromTemplate(arg1:string):Promise<main.WorkflowSummary>;

export function DeleteAIProvider(arg1:string):Promise<string>;

export function DeleteAction(arg1:string):Promise<void>;

export function DeleteSecret(arg1:string):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DeleteVaultImage(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function DenyOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteAction(arg1:string):Promise<void>;

export function ExportData():Promise<main.ExportResult>;

export function ExportVaultAll():Promise<main.VaultExportResult>;

export function GateApproveOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GateRejectOrgAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAIChatHistory(arg1:string):Promise<string>;

export function GetAIModels(arg1:string):Promise<string>;

export function GetAIRegistry():Promise<string>;

export function GetAction(arg1:string):Promise<main.ActionInfo>;

export function GetActionTargets(arg1:string):Promise<Array<main.TargetInfo>>;

export function GetActions(arg1:string,arg2:string,arg3:number):Promise<Array<main.ActionInfo>>;

export function GetActiveProfile():Promise<main.ProfileInfo>;

export function GetAllPersonMessages(arg1:number):Promise<Array<storage.PersonMessageWithPerson>>;

export function GetAllTags():Promise<Array<main.TagInfo>>;

export function GetAvailableActionTypes():Promise<Record<string, Array<string>>>;

export function GetConnectionsForPlatform(arg1:string):Promise<Array<connections.SafeConnection>>;

export function GetDBPath():Promise<string>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetDraftPersonMessages():Promise<Array<storage.PersonMessageWithPerson>>;

export function GetExecutionDetail(arg1:string):Promise<Record<string, any>>;

export function GetHILItems():Promise<Array<main.HILItem>>;

export function GetLatestPersonStatus(arg1:string):Promise<storage.PersonStatusUpdate>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetOAuthCredentials(arg1:string):Promise<string>;

export function GetOrgCosts(arg1:string):Promise<string>;

export function GetOrgDecisions(arg1:string):Promise<string>;

export function GetOrgFlow(arg1:string):Promise<string>;

export function GetOrgGates(arg1:string):Promise<string>;

export function GetOrgLogs(arg1:string):Promise<string>;

export function GetOrgMemoryStats(arg1:string):Promise<string>;

export function GetOrgQuestions(arg1:string):Promise<string>;

export function GetOrgReport(arg1:string,arg2:boolean):Promise<string>;

export function GetOrgStatus(arg1:string):Promise<string>;

export function GetPeople(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.PersonInfo>>;

export function GetPeopleCount(arg1:string,arg2:string):Promise<number>;

export function GetPeopleTagsMap(arg1:Array<string>):Promise<Record<string, Array<main.TagInfo>>>;

export function GetPersonDetail(arg1:string):Promise<main.PersonDetailInfo>;

export function GetPersonInteractions(arg1:string):Promise<Array<main.PersonInteraction>>;

export function GetPersonMessages(arg1:string):Promise<Array<storage.PersonMessage>>;

export function GetPersonPosts(arg1:string):Promise<Array<main.PostSummary>>;

export function GetPersonStatusHistory(arg1:string,arg2:number):Promise<Array<storage.PersonStatusUpdate>>;

export function GetPersonTags(arg1:string):Promise<Array<main.TagInfo>>;

export function GetPostComments(arg1:string):Promise<Array<main.PostComment>>;

export function GetPostDetail(arg1:string):Promise<main.PostDetail>;

export function GetProfiles():Promise<Array<main.ProfileInfo>>;

export function GetRecentExecutions(arg1:number):Promise<Array<main.WorkflowExecutionSummary>>;

export function GetSecretFields(arg1:string):Promise<main.VaultFieldsAndNotes>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSocialLists():Promise<Array<main.SocialListInfo>>;

export function GetTemplates():Promise<Array<main.TemplateInfo>>;

export function GetVaultImage(arg1:string):Promise<Record<string, any>>;

export function GetVaultImageData(arg1:string):Promise<string>;

export function GetVaultImages(arg1:number):Promise<Array<Record<string, any>>>;

export function GetVaultStats():Promise<Record<string, any>>;

export function GetVersion():Promise<main.VersionInfo>;

export function GetWorkflow(arg1:string):Promise<main.WorkflowDetail>;

export function GetWorkflowExecutions(arg1:string,arg2:number):Promise<Array<main.WorkflowExecutionSummary>>;

export function GetWorkflowNodeTypes():Promise<Record<string, any>>;

export function ImportVaultAll(arg1:string,arg2:string):Promise<main.VaultImportResult>;

export function IsDBConnected():Promise<boolean>;

export function ListAIProviders():Promise<string>;

export function ListConnections(arg1:string):Promise<Array<connections.SafeConnection>>;

export function ListCredentialsForNode(arg1:string):Promise<Array<main.CredentialOption>>;

export function ListOrgs():Promise<string>;

export function ListPlatformsJSON(arg1:string):Promise<string>;

export function ListResources(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ResourceListResult>;

export function ListSecrets():Promise<Array<main.VaultEntry>>;

export function ListWorkflowTemplates():Promise<Array<workflow.Template>>;

export function ListWorkflows():Promise<Array<main.WorkflowSummary>>;

export function LoginSocial(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenVaultFilePicker():Promise<string>;

export function OpenVaultImportFilePicker():Promise<string>;

export function RejectDraftPersonMessage(arg1:string):Promise<void>;

export function RejectHIL(arg1:string):Promise<void>;

export function RemoveConnection(arg1:string):Promise<string>;

export function RemovePersonTag(arg1:string,arg2:string):Promise<void>;

export function RunNode(arg1:main.NodeRunRequest):Promise<main.NodeRunResult>;

export function RunWorkflow(arg1:string):Promise<void>;

export function SaveAIProvider(arg1:string):Promise<string>;

export function SaveConnectionDirect(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveVaultImageToFile(arg1:string,arg2:string):Promise<string>;

export function SaveWorkflow(arg1:main.SaveWorkflowRequest):Promise<main.WorkflowSummary>;

export function ScanAgentRuntimes():Promise<string>;

export function SearchVaultImages(arg1:string):Promise<Array<Record<string, any>>>;

export function SelfUpdate():Promise<main.UpdateResult>;

export function SendDraftPersonMessage(arg1:string):Promise<storage.PersonMessage>;

export function SetOAuthCredentials(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetWorkflowActive(arg1:string,arg2:boolean):Promise<void>;

export function StopAIChat(arg1:string):Promise<string>;

export function StopAgentChat(arg1:string):Promise<string>;

export function StopOrgEvents(arg1:string):Promise<string>;

export function StreamAIChat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StreamAgentChat(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function StreamOrgEvents(arg1:string):Promise<string>;

export function SwitchProfile(arg1:string):Promise<void>;

export function TestAIProvider(arg1:string):Promise<string>;

export function TestConnection(arg1:string):Promise<string>;

export function TestSession(arg1:number):Promise<string>;

export function UpdateActionParams(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateActionState(arg1:string,arg2:string):Promise<void>;

export function UpdateSecret(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Record<string, string>):Promise<void>;

export function UpdateVaultImageLabel(arg1:string,arg2:string):Promise<void>;
